services:
  streamlit:
    build: ./app 
    image: streamlit:latest
    container_name: streamlit_container
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_HOST: "0.0.0.0"
      STREAMLIT_PORT: "8501"
      DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"

    volumes:
      - ./app:/app  
    networks:
      - app_network
    depends_on:
      - fastapi  

  fastapi:
    build: ./main
    image: fastapi:latest
    container_name: fastapi_container
    ports:
      - "8000:8000"
    environment:
      FASTAPI_HOST: "0.0.0.0"
      FASTAPI_PORT: "8000"
      DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"

    volumes:
      - ./main:/app
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


  

networks:
  app_network:
    driver: bridge
