version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - app_network
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    networks:
      - app_network
    depends_on:
      - backend
    ports:
      - "8501:8501"

networks:
  app_network:
    driver: bridge
