services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - ../.env # المسار الصحيح إلى ملف .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db.py:/shared/db.py
    networks:
      - app_network

  python_app:
    build:
      context: ./db-test
    container_name: db_test_container
    env_file:
      - ../.env # المسار الصحيح إلى ملف .env
    depends_on:
      - postgres
    volumes:
      - ./db-test:/app/db-test
      - ./db.py:/app/db.py  # مشاركة db.py مع التطبيق
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
